### ISSUE TITLE
입장하셨습니다 메시지가 2개 뜨는 현상

### ISSUE THREAD

**Issue by kingle1024** [kingle1024/DZ_Chat#9]
[재현 절차]
채팅방 생성 -> q -> 채팅방 입장

[실제 결과]
![image](https://user-images.githubusercontent.com/25365672/197081340-cc69d21c-1e1c-4da2-8867-e57a29a4387d.png)

[기대 결과]
입장하셨습니다 메시지 1개만 표시

**Comment by jhkim988** [comment]
해결 완료

**Comment by kingle1024** [comment]
10d68bde10cf102f91f2fb8716688aa6a8a2227b 에서 해결

**Comment by kingle1024** [comment]
확인 완료
![image](https://user-images.githubusercontent.com/25365672/197083156-7abc0dbf-2e13-4795-8424-ff0403bf325e.png)
